repos:
  - repo: local
    hooks:
      - id: talisman-precommit
        name: talisman
        entry: >-
          bash -c 'if [ -n "${TALISMAN_HOME:-}" ]; then
          ${TALISMAN_HOME}/talisman_hook_script pre-commit; else echo "TALISMAN
          does not exist. Consider installing from
          https://github.com/thoughtworks/talisman . If you already have
          talisman installed, please ensure TALISMAN_HOME variable is set to
          where talisman_hook_script resides, for example,
          TALISMAN_HOME=${HOME}/.talisman/bin"; fi'
        language: system
        pass_filenames: false
        types:
          - text
        verbose: true
  - repo: "https://github.com/pre-commit/mirrors-prettier"
    rev: v2.7.1
    hooks:
      - id: prettier
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.3.0
    hooks:
      - id: check-yaml
        name: Check YAML
        args:
          - "--allow-multiple-documents"
      - id: no-commit-to-branch
        name: No Commits to Master
        args:
          - "--branch=master"
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  # - repo: https://github.com/antonbabenko/pre-commit-terraform
  #   rev: v1.50.0
  #   hooks:
  #     - id: terraform_tfsec
